services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - NODE_ENV=production
      - DOTENV_KEY=${DOTENV_KEY} # Reference the DOTENV_KEY from your local environment
      - PORT=8081
    image: wrangel/globschi-backend:1.3-amd64
    ports:
      - "8081:8081"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: wrangel/globschi-frontend:1.3-amd64
    ports:
      - "80:80"
