version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - NODE_ENV=production
      - DOTENV_KEY=${DOTENV_KEY}
      - PORT=8081
      # You don't need to explicitly set these as they will be loaded from dotenv-vault
      # - DB_USER
      # - DB_PASSWORD
      # - SERVER
      # - DB
    ports:
      - "8081:8081"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
