services:
  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=8081
    image: wrangel/globschi-backend:1.4
    ports:
      - "8081:8081"

  frontend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_GOOGLE_MAPS_API_KEY: ${VITE_GOOGLE_MAPS_API_KEY}
        VITE_MAPBOX_ACCESS_TOKEN: ${VITE_MAPBOX_ACCESS_TOKEN}
    image: wrangel/globschi-frontend:1.4
    ports:
      - "3000:80"
