services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - NODE_ENV=production
      - DOTENV_KEY=${DOTENV_KEY} # Reference the DOTENV_KEY from your local environment or .env file
      - PORT=8081
    ports:
      - "8081:8081"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
