services:
  app:
    build: .
    ports:
      - "8081:8081" # Backend port
      - "3000:3000" # Frontend port
    environment:
      - NODE_ENV=development
      - PORT=8081
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVER=${SERVER}
      - DB=${DB}
    volumes:
      - .:/usr/src/app
    command: ["pnpm", "run", "dev"]

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
