allowBuilds:
  sharp: true

onlyBuiltDependencies:
  - sharp

overrides:
  shell-quote: ">=1.8.5"
  "three@<0.125.0": ">=0.125.0"
  "postcss@<8.4.31": ">=8.4.31"
  "nth-check@<2.0.1": ">=2.0.1"
  "serialize-javascript@<6.0.2": ">=6.0.2"
  "react-router@<7.5.2": ">=7.5.2"
  "tmp@<=0.2.3": ">=0.2.4"
