name: CI Workflow

on:
  push:
    branches:
      - main
      - "feature/*"
      - "bugfix/*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a simple command
        run: echo "Building and testing..."
